# Generated by Django 4.2.5 on 2023-10-12 13:17
from django.db import migrations

def populate_required_tables(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    MessageType = apps.get_model('board_app', 'MessageType')
    Category = apps.get_model('board_app', 'Category')
    for type in ('chat', 'follow'):
        MessageType.objects.create(name=type)
        
    for category in ('Танки', 'Хилы', 'ДД', 'Торговцы', 'Гилдмастеры', 'Квестгиверы', 
                     'Кузнецы', 'Кожевники','Зельевары', 'Мастера заклинаний'):
        Category.objects.create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0001_initial"),
    ]

    operations = [ migrations.RunPython(populate_required_tables),
]
