# Generated by Django 4.2.5 on 2023-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0002_auto_20231012_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="img_thumb",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
